export const comboData = [
  {
    id: 1,
    name: 'Topic on .NET Programming',
    code: 'SE_COM3',
    syllabi: [
      {
        id: 4,
        name: 'Syllabus 4',
        subject: null,
        code: null,
        noCredit: 0,
        noSlot: 0,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        referenceSyllabusInCombo: null,
        active: false,
        syllabusCombo: false,
      },
      {
        id: 5,
        name: 'Syllabus 5',
        subject: null,
        code: null,
        noCredit: 0,
        noSlot: 0,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        referenceSyllabusInCombo: null,
        active: false,
        syllabusCombo: false,
      },
      {
        id: 6,
        name: 'Syllabus 6',
        subject: null,
        code: null,
        noCredit: 0,
        noSlot: 0,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        referenceSyllabusInCombo: null,
        active: false,
        syllabusCombo: false,
      },
      {
        id: 7,
        name: 'Syllabus 7',
        subject: null,
        code: null,
        noCredit: 0,
        noSlot: 0,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        referenceSyllabusInCombo: null,
        active: false,
        syllabusCombo: false,
      },
      {
        id: 8,
        name: 'Syllabus 8',
        subject: null,
        code: null,
        noCredit: 0,
        noSlot: 0,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        referenceSyllabusInCombo: null,
        active: false,
        syllabusCombo: false,
      },
    ],
    active: true,
  },
];
