import { Group, GroupType } from 'src/@types';
export const groupData: Group[] = [
  {
    id: 1,
    name: 'CLASS',
    type: GroupType.Class,
    conversationId: null,
    createdDateTime: '2023-02-18T15:36:03.673711',
    curriculum: {
      id: 2,
      name: null,
      code: 'SE15',
      schoolYear: null,
      description: null,
      major: null,
      specialization: null,
      startedTerm: null,
      noSemester: 9,
      currentSemester: 9,
      active: true,
    },
    syllabus: null,
    teacher: null,
    private: false,
    active: false,
  },
  {
    id: 2,
    name: 'COURSE COURSE',
    type: GroupType.Course,
    conversationId: null,
    createdDateTime: '2023-02-18T15:37:40.14811',
    curriculum: {
      id: 2,
      name: null,
      code: 'SE15',
      schoolYear: null,
      description: null,
      major: null,
      specialization: null,
      startedTerm: null,
      noSemester: 9,
      currentSemester: 9,
      active: true,
    },
    syllabus: {
      id: 1,
      name: 'Test',
      code: '1',
      subject: null,
      noCredit: 3,
      noSlot: 20,
      duration: null,
      preRequisite: null,
      description: null,
      minAvgMarkToPass: 2,
      active: true,
    },
    teacher: {
      id: 1,
      name: 'trang',
      code: null,
      role: 'STUDENT',
      schoolYear: null,
      personalMail: null,
      eduMail: null,
      avatar: null,
      phoneNumber: null,
      curriculum: null,
      active: true,
    },
    private: false,
    active: false,
  },
  {
    id: 3,
    name: 'CLASS',
    type: GroupType.Class,
    conversationId: null,
    createdDateTime: '2023-02-18T15:38:45.634926',
    curriculum: {
      id: 2,
      name: null,
      code: 'SE15',
      schoolYear: null,
      description: null,
      major: null,
      specialization: null,
      startedTerm: null,
      noSemester: 9,
      currentSemester: 9,
      active: true,
    },
    syllabus: null,
    teacher: null,
    private: false,
    active: true,
  },
  {
    id: 4,
    name: 'DEPARTMENT',
    type: GroupType.Department,
    conversationId: null,
    createdDateTime: '2023-02-18T15:38:58.785259',
    curriculum: null,
    syllabus: null,
    teacher: null,
    private: true,
    active: false,
  },
  {
    id: 5,
    name: 'NORMAL-Update',
    type: GroupType.Normal,
    conversationId: null,
    createdDateTime: '2023-02-18T16:15:34.900491',
    curriculum: null,
    syllabus: null,
    teacher: null,
    private: false,
    active: true,
  },
  {
    id: 6,
    name: 'CLASS',
    type: GroupType.Class,
    conversationId: null,
    createdDateTime: '2023-02-18T15:54:28.716572',
    curriculum: {
      id: 2,
      name: null,
      code: 'SE15',
      schoolYear: null,
      description: null,
      major: null,
      specialization: null,
      startedTerm: null,
      noSemester: 9,
      currentSemester: 9,
      active: true,
    },
    syllabus: null,
    teacher: null,
    private: false,
    active: true,
  },
];
