import { Subject } from 'src/@types';

export const subjectData: Subject[] = [
  {
    id: 1,
    name: 'Bo mon Toan',
    code: 'MATT',
    subjects: [
      {
        id: 6,
        name: 'Toan',
        code: 'MAT',
        subjects: null,
        active: false,
        combo: false,
      },
      {
        id: 7,
        name: 'Toan 2',
        code: 'MAT102',
        subjects: null,
        active: false,
        combo: false,
      },
    ],
    active: true,
    combo: true,
  },
  {
    id: 2,
    name: 'Bo mon Toan 2',
    code: 'MATT2',
    subjects: [
      {
        id: 1,
        name: 'Bo mon Toan',
        code: 'MATT',
        subjects: [
          {
            id: 6,
            name: 'Toan',
            code: 'MAT',
            subjects: null,
            active: false,
            combo: false,
          },
          {
            id: 7,
            name: 'Toan 2',
            code: 'MAT102',
            subjects: null,
            active: false,
            combo: false,
          },
        ],
        active: true,
        combo: true,
      },
      {
        id: 7,
        name: 'Toan 2',
        code: 'MAT102',
        subjects: null,
        active: false,
        combo: false,
      },
    ],
    active: true,
    combo: true,
  },
  {
    id: 3,
    name: 'Khoa hoc',
    code: 'KH',
    subjects: [
      {
        id: 1,
        name: 'Bo mon Toan',
        code: 'MATT',
        subjects: [
          {
            id: 6,
            name: 'Toan',
            code: 'MAT',
            subjects: null,
            active: false,
            combo: false,
          },
          {
            id: 7,
            name: 'Toan 2',
            code: 'MAT102',
            subjects: null,
            active: false,
            combo: false,
          },
        ],
        active: true,
        combo: true,
      },
      {
        id: 2,
        name: 'Bo mon Toan 2',
        code: 'MATT2',
        subjects: [
          {
            id: 1,
            name: 'Bo mon Toan',
            code: 'MATT',
            subjects: [
              {
                id: 6,
                name: 'Toan',
                code: 'MAT',
                subjects: null,
                active: false,
                combo: false,
              },
              {
                id: 7,
                name: 'Toan 2',
                code: 'MAT102',
                subjects: null,
                active: false,
                combo: false,
              },
            ],
            active: true,
            combo: true,
          },
          {
            id: 7,
            name: 'Toan 2',
            code: 'MAT102',
            subjects: null,
            active: false,
            combo: false,
          },
        ],
        active: true,
        combo: true,
      },
    ],
    active: true,
    combo: true,
  },
  {
    id: 6,
    name: 'Toan',
    code: 'MAT',
    subjects: null,
    active: false,
    combo: false,
  },
  {
    id: 7,
    name: 'Toan 2',
    code: 'MAT102',
    subjects: null,
    active: false,
    combo: false,
  },
  {
    id: 8,
    name: 'Bo mon Ngu van 2',
    code: 'NV2',
    subjects: [
      {
        id: 6,
        name: 'Toan',
        code: 'MAT',
        subjects: null,
        active: false,
        combo: false,
      },
      {
        id: 7,
        name: 'Toan 2',
        code: 'MAT102',
        subjects: null,
        active: false,
        combo: false,
      },
    ],
    active: false,
    combo: true,
  },
  {
    id: 9,
    name: 'string',
    code: null,
    subjects: null,
    active: true,
    combo: false,
  },
];
