import { Syllabus } from 'src/@types';

export const syllabusData: Syllabus[] = [
  {
    id: 1,
    name: 'Syllabus 111',
    code: '1',
    subject: {
      id: 2,
      name: 'Bo mon Toan 2',
      code: 'MATT2',
      subjects: [
        {
          id: 1,
          name: null,
          code: null,
          subjects: null,
          active: false,
          combo: false,
        },
        {
          id: 7,
          name: null,
          code: null,
          subjects: null,
          active: false,
          combo: false,
        },
      ],
      active: true,
      combo: true,
    },
    noCredit: 5,
    noSlot: 35,
    duration: 100,
    preRequisite: null,
    description: 'djsakldjsakl;dasjkdl;as',
    minAvgMarkToPass: 5,
    active: true,
  },
  {
    id: 2,
    name: 'Syllabus 2',
    code: '1',

    subject: {
      id: 1,
      name: 'Bo mon Toan',
      code: 'MATT',
      subjects: [
        {
          id: 6,
          name: null,
          code: null,
          subjects: null,
          active: false,
          combo: false,
        },
        {
          id: 7,
          name: null,
          code: null,
          subjects: null,
          active: false,
          combo: false,
        },
      ],
      active: true,
      combo: true,
    },
    noCredit: 3,
    noSlot: 30,
    duration: 90,
    preRequisite: [
      {
        id: 1,
        name: null,
        code: '1',

        subject: null,
        noCredit: 0,
        noSlot: 0,
        duration: null,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        active: false,
      },
    ],
    description: 'djsakldjsakl;dasjkdl;as',
    minAvgMarkToPass: 4,
    active: true,
  },
  {
    id: 3,
    name: 'Syllabus 3',
    code: '1',
    subject: {
      id: 2,
      name: 'Bo mon Toan 2',
      code: 'MATT2',
      subjects: [
        {
          id: 1,
          name: null,
          code: null,
          subjects: null,
          active: false,
          combo: false,
        },
        {
          id: 7,
          name: null,
          code: null,
          subjects: null,
          active: false,
          combo: false,
        },
      ],
      active: true,
      combo: true,
    },
    noCredit: 3,
    noSlot: 30,
    duration: 90,
    preRequisite: [
      {
        id: 1,
        name: null,
        code: '1',

        subject: null,
        noCredit: 0,
        noSlot: 0,
        duration: null,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        active: false,
      },
      {
        id: 2,
        name: null,
        code: '1',
        subject: null,
        noCredit: 0,
        noSlot: 0,
        duration: null,
        preRequisite: null,
        description: null,
        minAvgMarkToPass: 0,
        active: false,
      },
    ],
    description: 'djsakldjsakl;dasjkdl;as',
    minAvgMarkToPass: 4,
    active: true,
  },
];
