name: CI to Docker Hub
# event happen
on:
  push:
    branches: [dev]
env:
  IMAGE_NAME: funiverse/funiverse-web-sa
  FILE_PATH: config/frontend/system-admin-deployment.yaml
  APP_NAME: Workspace System Admin Webapp
# JOBs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #save cache for not re-downloading images again
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Checkout repository
        uses: actions/checkout@v3
      #login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/funiverse-web-sa:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Build ${{env.APP_NAME}} Successfully!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            Build ${{env.APP_NAME}} Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    outputs:
      version: ${{steps.docker_build.outputs.digest}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Infra Config Repo
        uses: actions/checkout@v3
        with:
          repository: FUnigrad/funiverse-infra-config
          token: ${{secrets.PUSH_GITHUB_TOKEN}}
          ref: dev
      - name: Get Version
        run: echo "VERSION=${{needs.build.outputs.version}}" >> $GITHUB_ENV
      - name: Update Manifest
        run: |
          sed -i "s+${{env.IMAGE_NAME}}.*+${{env.IMAGE_NAME}}@${{env.VERSION}}+g" ${{env.FILE_PATH}}
      - name: Commit and push
        run: |
          git config --global user.name 'nqbao11'
          git config --global user.email 'nqbao11.01@gmail.com'
          git commit -am "deployed latest ${{env.IMAGE_NAME}} by https://github.com/${{github.repository}}/commit/${{github.event.pull_request.head.sha}}"
          git push
      - name: Deploy Failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            Deploy ${{env.APP_NAME}} Failed!
            Check log in github action
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Deploy ${{env.APP_NAME}} Successfully!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
